### PR TITLE
Disable WAL

### LINKED ISSUE #1760: Unclean node shutdown causes crash on future startups
I've seen this on two different nodes (on windows with latest nightly build)

```
C:\>"C:\Program Files\Ethcore\Parity\parity.exe" --tracing on --port 30305 --jsonrpc-port
8546
2016-07-29 02:35:26 UTCStarting Parity/v1.3.0-unstable-e4f0c0b-20160728/x86_64-windows-msv
c/rustc1.10.0
2016-07-29 02:35:26 UTCUsing state DB journalling strategy fast
2016-07-29 02:35:26 UTCImport geth accounts failed. The system cannot find the path specif
ied. (os error 3)
2016-07-29 02:35:27 UTCConfigured for Frontier/Homestead using Ethash engine
thread '<main>' panicked at 'called `Option::unwrap()` on a `None` value', ../src/libcore\
option.rs:325
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

This occurred directly on startup, there were no background RPC calls occuring

### PR DESCRIPTION
**Pull request by arkpar**
https://github.com/facebook/rocksdb/wiki/Known-Issues
"Atomicity is not guaranteed after DB recovery for more than one multiple column families and WAL is disabled."

This makes import 5% slower but guarantees DB recovery.
should also fix #1760

### CODE REVIEW

**Comment by gavofyork** [comment]
probably worth having WAL optional but defaulting to off.

**Comment by gavofyork** [comment]
(i'm working on that now.)

File: parity/cli.rs [hunk 1]
```diff
@@ -314,6 +314,7 @@ pub struct Args {
 	pub flag_cache_size_queue: u32,
 	pub flag_cache_size: Option<u32>,
 	pub flag_cache: Option<u32>,
+  pub flag_fast_and_loose: bool,
```
Comment (arkpar) [inline parity/cli.rs]: Indentation
