### PR TITLE
Trace filtering fix

### LINKED ISSUE #2751: Trace Filter is not working properly (filtering fromAddress)
When trying to use the `trace_filter` call with the `fromAddress` filter, some unrelated transactions are returned.

Eg. for address `0xe1a1531a6667fa8ba694692362fc679105ff2677` on Testnet.

There should be only one **IN** transaction : https://testnet.etherscan.io/address/0xe1a1531a6667fa8ba694692362fc679105ff2677

However, running 
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"trace_filter","params":[{"fromBlock":"0x0","fromAddress":["0xE1A1531A6667FA8ba694692362Fc679105ff2677"]}],"id":74}' localhost:8545 | python -mjson.tool
```
will return 2 contract creation transactions unrelated to the account `0xe1a1531a6667fa8ba694692362fc679105ff2677` ([0xdf92bf2](http://testnet.etherscan.io/tx/0xdf92bf2be3547fc456e51db27450c8ac1accfc85e2a5618ef880a215d7fc6046) and [0x85893ad](http://testnet.etherscan.io/tx/0x85893ad8ce27faaa2bf27ae05139618630d9f755254b9cf042804014152aff09)).

It seems that it returns every contract creation transactions ([filter.rs#L130](https://github.com/ethcore/parity/blob/master/ethcore/src/types/trace_types/filter.rs#L130) with no `to_address` filter), in blocks matching the `toAddress` filter...

### PR DESCRIPTION
**Pull request by ngotchac**
Fixes #2751 

Don't test contract address against empty `toAddress` array in trace filtering.

### CODE REVIEW

File: ethcore/src/types/trace_types/filter.rs [hunk 1]
```diff
@@ -42,8 +42,13 @@ impl From<Vec<Address>> for AddressesFilter {
 impl AddressesFilter {
 	/// Returns true if address matches one of the searched addresses.
 	pub fn matches(&self, address: &Address) -> bool {
-		self.matches_all() || self.list.contains(address)
-	}
+		self.matches_all() || self.stricly_matches(address)
+    }
```
Comment (rphmeier) [inline ethcore/src/types/trace_types/filter.rs]: extra space here

Comment (ngotchac) [inline ethcore/src/types/trace_types/filter.rs]: Yep just saw that

File: ethcore/src/types/trace_types/filter.rs [hunk 2]
```diff
@@ -42,8 +42,13 @@ impl From<Vec<Address>> for AddressesFilter {
...
+
+    /// Returns true if address matches at least one of the searched addresses.
+    pub fn stricly_matches(&self, address: &Address) -> bool {
```
Comment (ngotchac) [inline ethcore/src/types/trace_types/filter.rs]: Ah...

File: ethcore/src/types/trace_types/filter.rs [hunk 3]
```diff
@@ -127,7 +132,7 @@ impl Filter {
 		};
 
 		action || match trace.result {
-			Res::Create(ref create) => self.to_address.matches(&create.address),
+			Res::Create(ref create) => self.to_address.stricly_matches(&create.address),
```
Comment (ngotchac) [inline ethcore/src/types/trace_types/filter.rs]: Yes that would be totally equivent.

Comment (ngotchac) [inline ethcore/src/types/trace_types/filter.rs]: However the `address` field is in the `result` _part_ of the trace, not in the action

File: ethcore/src/types/trace_types/filter.rs [hunk 4]
```diff
@@ -108,27 +108,27 @@ impl Filter {
...
 			Action::Call(ref call) => {
 				let from_matches = self.from_address.matches(&call.from);
 				let to_matches = self.to_address.matches(&call.to);
 				from_matches && to_matches
 			}
 			Action::Create(ref create) => {
 				let from_matches = self.from_address.matches(&create.from);
-				let to_matches = self.to_address.matches_all();
+
+				let to_matches = match trace.result {
```
Comment (tomusdrw) [inline ethcore/src/types/trace_types/filter.rs]: Hmm, now that I saw it's coming from `result` I'm not sure if it's equivalent.
@debris is it possible that `trace.action` is `Action::Call` but the result is `Res::Create` somehow?

Comment (debris) [inline ethcore/src/types/trace_types/filter.rs]: No. To be honest, there should be just one enum. Having two is just a performance workaround to avoid unnecessary copying data when trace is created.
