### PR TITLE
Fixing minimal transaction queue price

### LINKED ISSUE #4198: ZGP transactions might be accepted to queue right after start
With default settings we have
```
--usd-per-tx 0.0025
```
So transactions below this threshold shouldn't be accepted to the queue.

There is a small window though, before we initially fetch the price, where queue will accept ZGP. Initially it should probably set minimal gas price according to last known ETH price.

### LINKED ISSUE #4199: Minimal Gas Price not set correctly
1.4.9 Running with default settings for `--usd-per-tx, et al`
```
curl -H "Content-Type: application/json" -X POST --data '{"jsonrpc":"2.0","method":"parity_minGasPrice","params":[],"id":83}' http://127.0.0.1:8545

{"jsonrpc":"2.0","result":"0x0","id":83}
```

Should return a valid gas price based on current ETH/USD rate

### PR DESCRIPTION
**Pull request by tomusdrw**
Closes #4199 
Closes #4198

### CODE REVIEW

File: ethcore/src/miner/miner.rs [hunk 1]
```diff
@@ -1123,6 +1123,9 @@ impl MinerService for Miner {
 		// First update gas limit in transaction queue
 		self.update_gas_limit(chain);
 
+		// Update minimal gas price
+		self.recalibrate_minimal_gas_price();
```
Comment (rphmeier) [inline ethcore/src/miner/miner.rs]: wouldn't this lead to sending off an HTTP request every time `chain_new_blocks` is called?

Comment (tomusdrw) [inline ethcore/src/miner/miner.rs]: Previously it was done in `prepare_block`, so for mining nodes it was the same (`chain_new_blocks` even is not sent to miner if we're syncing afaik)
Also `GasCalibrator` supports a minimal interval between calibrations:
https://github.com/ethcore/parity/blob/8517369372f2e151dedf5d6f1b6c32bd372453da/ethcore/src/miner/miner.rs#L147-L167
so I don't see an issue here.

Comment (rphmeier) [inline ethcore/src/miner/miner.rs]: Yes, I see now, just leaving a comment as I skimmed through it
