### PR TITLE
Sync fixes and tweaks

### LINKED ISSUE #1159: Parity sync process comes to a halt with only 1 active peer and 0 blk/s
Hi,

I'm running Parity/v1.2.0-unstable-94ec245-20160526/aarch64-linux-gnu/rustc1.10.0-beta.1 on an ODROID C2, which syncs to a USB stick on a 32 Mbps Internet connection (no wifi used).

This is a snippet from stdout just before it starts to come to a halt and not import any new blocks.
https://gist.github.com/timjp87/fca440450828c169491c7ce3e7e33c56

I used -l sync=trace and redirected stderr to a file.

[sync.txt](https://github.com/ethcore/parity/files/286506/sync.txt)

When using geth the C2 doesn't seem to have any problems syncing the chain.

### PR DESCRIPTION
**Pull request by arkpar**
Fixes #1159

### CODE REVIEW

File: sync/src/chain.rs [hunk 1]
```diff
@@ -862,16 +863,12 @@ impl ChainSync {
...
-				debug!(target:"sync", "Error sending request: {:?}", e);
-				sync.disable_peer(peer_id);
-			}
-			Ok(_) => {
-				let mut peer = self.peers.get_mut(&peer_id).unwrap();
-				peer.asking = asking;
-				peer.ask_time = time::precise_time_s();
-			}
+		let mut peer = self.peers.get_mut(&peer_id).unwrap();
+		peer.asking = asking;
```
Comment (arkpar) [inline sync/src/chain.rs]: Always set the asking status so that requested blocks would be unmarked as being downloaded on disconnect.

File: sync/src/chain.rs [hunk 2]
```diff
@@ -1259,15 +1257,15 @@ impl ChainSync {
 	}
 
 	fn propagate_latest_blocks(&mut self, io: &mut SyncIo) {
```
Comment (arkpar) [inline sync/src/chain.rs]: Changed the propagation order here to give uncles prioriy

File: sync/src/chain.rs [hunk 3]
```diff
@@ -862,16 +863,12 @@ impl ChainSync {
 				warn!(target:"sync", "Asking {:?} while requesting {:?}", peer.asking, asking);
 			}
 		}
```
Comment (rphmeier) [inline sync/src/chain.rs]: taking this code out of a nested block would prevent a second hashmap lookup

File: sync/src/tests/chain.rs [hunk 4]
```diff
@@ -159,7 +159,7 @@ fn propagate_hashes() {
 
 #[test]
 fn propagate_blocks() {
-	let mut net = TestNet::new(2);
+	let mut net = TestNet::new(20);
```
Comment (NikVolf) [inline sync/src/tests/chain.rs]: shouldn't it also work for a small number of peers?

Comment (arkpar) [inline sync/src/tests/chain.rs]: Now the NewHashes message is sent out first, than NewBlock to some of the remaining peers. So this test requires more peers
