### PR TITLE
Security audit issues fixed

### LINKED ISSUE #1276: [Sec Audit] 004 Parity Panic via Integer Overflow in Block Genesis File
When defining a new chain with a JSON configuration file, certain fields are assigned as large integers which is defined in the `BigInt` library of the Parity client. Large integers in this library can be overflowed which will cause a panic.

### PR DESCRIPTION
**Pull request by arkpar**
Fixes #1276, #1277, #1278

### CODE REVIEW

File: util/src/rlp/untrusted_rlp.rs [hunk 1]
```diff
@@ -334,9 +334,9 @@ impl<'a> BasicDecoder<'a> {
 	/// Return first item info.
 	fn payload_info(bytes: &[u8]) -> Result<PayloadInfo, DecoderError> {
 		let item = try!(PayloadInfo::from(bytes));
-		match item.header_len + item.value_len <= bytes.len() {
-			true => Ok(item),
-			false => Err(DecoderError::RlpIsTooShort),
+		match item.header_len.checked_add(item.value_len) { 
+			Some(x) if x <= bytes.len() => Ok(item), 
+			_ => Err(DecoderError::RlpIsTooShort),
```
Comment (debris) [inline util/src/rlp/untrusted_rlp.rs]: It's too short, but in the same time, the length is just invalid ;)

File: util/src/network/host.rs [hunk 2]
```diff
@@ -946,13 +947,17 @@ fn save_key(path: &Path, key: &Secret) {
...
+	let mut file = match fs::File::create(&path) {
 		Ok(file) => file,
 		Err(e) => {
 			warn!("Error creating key file: {:?}", e);
 			return;
 		}
 	};
+	if let Err(e) = restrict_permissions_owner(&path) {
+		warn!(target: "network", "Failed to modify permissions of the file (chmod: {})", e);
+	}
```
Comment (rphmeier) [inline util/src/network/host.rs]: might be better to die here rather than continue on in a potentially vulnerable state?

Comment (arkpar) [inline util/src/network/host.rs]: it is not that critical
