### PR TITLE
Token sorting, zero-ETH transfer & token decimals

### LINKED ISSUE #278: block_queue::tests::returns_error_for_verified_duplicates randomly fails
test `block_queue::tests::returns_error_for_verified_duplicates` randomly fails from time to time

see:

https://travis-ci.com/ethcore/parity/jobs/31862501

### LINKED ISSUE #2274: More descriptive error messages when an account has tokens but not ether and tries to transfer
Currently displays token balances at zero..

### LINKED ISSUE #2799: Token transfers should check for decimals
i.e. when beercoin doesn't have decimals, it makes no sense trying to transfer 0.9

### LINKED ISSUE #2814: When no ETH is an account, Tokens display the wrong values

### PR DESCRIPTION
**Pull request by jacogr**
- Don't allow transfer of 1.234 tokens when no decimals allowed, i.e. check decimals on value selection - Fixes #2799
- Sort tokens by tag (shows up sorted in balance as well as selection dropdowns) - Closes #278
- Always display the required ETH for calculations - Fixes #2814, Fixes #2274

### CODE REVIEW

File: js/src/modals/Transfer/Details/details.js [hunk 1]
```diff
@@ -129,7 +129,9 @@ export default class Details extends Component {
         if (isEth) {
           value = api.util.fromWei(balance.value).toFormat(3);
         } else {
-          value = new BigNumber(balance.value).div(balance.token.format || 1).toFormat(3);
+          const format = balance.token.format || 1;
+          const decimals = Math.min(3, format === 1 ? 0 : Math.floor(format / 10));
```
Comment (ngotchac) [inline js/src/modals/Transfer/Details/details.js]: Why not `format === 1 ? 0 : Math.min(3, Math.floor(format / 10))`

Comment (jacogr) [inline js/src/modals/Transfer/Details/details.js]: Probably a bit cleaner juggling it like that, at least a bit more understandable. Will update.
