### PR TITLE
Fix peers not displaying

### LINKED ISSUE #3558: Peers not displayed correctly
parity 2016-11-21 17-43-23

jacogreeff parity --ui-no-validation --chain ropsten parity --ui-no-validation --chain ropsten 238x58 2016-11-21 17-44-04

### PR DESCRIPTION
**Pull request by ngotchac**
Fixes #3558

### CODE REVIEW

File: js/src/redux/providers/status.js [hunk 1]
```diff
@@ -155,24 +155,24 @@ export default class Status {
...
+    const statusPromises = [ this._api.eth.syncing(), this._api.parity.netPeers() ];
 
     if (refreshStatus) {
       statusPromises.push(this._api.eth.hashrate());
-      statusPromises.push(this._api.parity.netPeers());
     }
 
     Promise
       .all(statusPromises)
       .then((statusResults) => {
```
Comment (derhuerst) [inline js/src/redux/providers/status.js]: You could use Array destructuring here and then check for existence:

```js
([ syncing, netPeers ]) => {
  if (syncing && netPeers) {
    …
  }
}

Comment (jacogr) [inline js/src/redux/providers/status.js]: Agreed here with @derhuerst - put the optional ones at the back, check for undefined if you must (then not adding it), but just cleaner.
