### PR TITLE
Fix Secure API hangs

### LINKED ISSUE #3811: Slowness and hangs related to "Connecting to the Parity Secure API"
I've compiled parity myself (master branch, labeled as 1.5.0-beta), and it seems to work ok on the MainNet.

However, if I run it with flag `--chain=classic`, I then cannot connect to the UI (in http://localhost:8080/) anymore. When I do that, it tries to redirect me to http://127.0.0.1:8180/#/accounts but it stays there with the message "Connecting to the Parity Secure API" and I cannot do anything else.

### PR DESCRIPTION
**Pull request by ngotchac**
Fixes #3811 

The Secure API has been partially rewritten, and is using Promise based connection. No unnecessary calls are made, and the right endpoint is used (previously, 8180 was used in Dev).

Small changes to Wepback have been made to reduce script files size. Firefox still has some troubles (freezes) loading the UI when dev tools is open. Seems to be fine otherwise.

### CODE REVIEW

File: js/src/secureApi.js [hunk 1]
```diff
@@ -20,122 +20,109 @@ const sysuiToken = window.localStorage.getItem('sysuiToken');
...
     this._needsToken = false;
+
     this._dappsPort = 8080;
     this._dappsInterface = null;
     this._signerPort = 8180;
-    this._followConnectionTimeoutId = null;
 
     // Try tokens from localstorage, then from hash
-    this._tokensToTry = [ sysuiToken, nextToken ].filter((t) => t && t.length);
+    this._tokens = [
```
Comment (jacogr) [inline js/src/secureApi.js]: What about this case - https://github.com/ethcore/parity/issues/3620

(In this case there is a sysuiToken, however we need to try with `initial` to generate a token. Basically would try `nextToken || 'initial'` on line 36, i.e. in this case these is a syuiToken, but won't be a nextToken - first would fail, second would succeed)

**Comment by jacogr** [comment]
Much cleaner. Would just explicitly cater for the case where the store is cleared, sysuiToken is thus invalid and we never try `'initial'` (comment in the code)

**Comment by ngotchac** [comment]
Should be ok now !

**Comment by jacogr** [comment]
Great. Just going to give it a run-through with scenarios, but code looks good.

**Comment by jacogr** [comment]
Tested with valid, invalid, auth passed, initial, all seems to be on-spec.
