### PR TITLE
Fixes pending/mined transactions in registry dApp

### LINKED ISSUE #2930: Pending/Mined transactions doubling up on Registry
pasted image at 2016_10_28 09_45 am

(via @gavofyork )

### PR DESCRIPTION
**Pull request by ngotchac**
Fixes #2930 

Also fixes some small React errors popping out

### CODE REVIEW

File: js/src/dapps/registry/Accounts/accounts.js [hunk 1]
```diff
@@ -49,7 +49,9 @@ export default class Accounts extends Component {
         value={ selected ? this.renderAccount(selected) : null }
         onChange={ this.onAccountSelect }
         iconButtonElement={ accountsButton }
-        animated={ false }
+
+        anchorOrigin={ { horizontal: 'right', vertical: 'top' } }
```
Comment (jacogr) [inline js/src/dapps/registry/Accounts/accounts.js]: Could we make this a constant, i.e.

```
const origin = { horizontal: 'right, vertical: 'top' };
...
<SomeTag
  anchorOrigin={ origin }
  targetOrigin={ origin }
```

**Comment by jacogr** [comment]
One small comment, but apart from that, ok.
