### PR TITLE
Fix issues with no ethereum test dir present (2382)

### LINKED ISSUE #2382: parity doesn't start if used both --testnet --geth parameters
Start parity with:

Parity version Parity/v1.3.1-beta-2a82fa0-20160911/x86_64-linux-gnu/rustc1.11.0

`parity --testnet --geth`

If there is no ~/.ethereum/testnet directory created before start it will fail with:

`RPC io error: No such file or directory (os error 2)`

### PR DESCRIPTION
**Pull request by NikVolf**
fixes #2382

### CODE REVIEW

File: parity/configuration.rs [hunk 1]
```diff
@@ -564,10 +564,10 @@ impl Configuration {
 		let dapps_path = replace_home(&self.args.flag_dapps_path);
 		let signer_path = replace_home(&self.args.flag_signer_path);
 
-		if self.args.flag_geth {
-			let geth_path = path::ethereum::default();
-			::std::fs::create_dir_all(geth_path.as_path()).unwrap_or_else(
-				|e| warn!("Failed to create '{}' for geth mode: {}", &geth_path.to_str().unwrap(), e));
+		if self.args.flag_geth  && !cfg!(windows) {
```
Comment (tomusdrw) [inline parity/configuration.rs]: What's wrong with Windows?

Comment (NikVolf) [inline parity/configuration.rs]: no need to create directory for windows pipe, it is in no way related to the file system

Comment (tomusdrw) [inline parity/configuration.rs]: I see, it's probably used in geth imports, but I think it handles missing directories correctly.
