### PR TITLE
Better handling of multiple migrations

### LINKED ISSUE #1745: 6 to 8 db migration fails
As mentioned in #1726. 6 to 7 and 7 to 8 works.

### PR DESCRIPTION
**Pull request by keorn**
Closes #1745

### CODE REVIEW

File: util/src/migration/mod.rs [hunk 1]
```diff
@@ -235,10 +236,11 @@ impl Manager {
...
 	}
 
-	fn migrations_from(&mut self, version: u32) -> Option<&mut [Box<Migration>]> {
-		// index of the first required migration
-		let position = self.migrations.iter().position(|m| m.version() == version + 1);
-		position.map(move |p| &mut self.migrations[p..])
+	/// Find all needed migrations and arrange them.
+	fn migrations_from(&mut self, version: u32) -> Vec<&mut Box<Migration>> {
+		let mut to_apply: Vec<_> = self.migrations.iter_mut().filter(|m| m.version() > version).collect();
+		to_apply.sort_by_key(|m| m.version());
```
Comment (tomusdrw) [inline util/src/migration/mod.rs]: Why is this needed? We already have a check in `add_migration`, no?

**Comment by tomusdrw** [comment]
There is also order assumption here: https://github.com/ethcore/parity/blob/3d38e05879f52176e78feeade1ee0ec37c9cb11d/util/src/migration/mod.rs#L233
Probably should be addressed.

File: util/src/migration/mod.rs [hunk 2]
```diff
@@ -209,7 +209,7 @@ impl Manager {
 		// start with the old db.
 		let old_path_str = try!(old_path.to_str().ok_or(Error::MigrationImpossible));
 		let mut cur_db = try!(Database::open(&db_config, old_path_str).map_err(Error::Custom));
-		for migration in migrations {
+		for migration in migrations.iter_mut() {
```
Comment (tomusdrw) [inline util/src/migration/mod.rs]: https://github.com/Manishearth/rust-clippy/wiki#explicit_iter_loop
