### PR TITLE
More sync and propagation fixes

### LINKED ISSUE #419: Panic during sync with 'new peer already exists'
two nodes, same machine, one was syncing from the other.

```
[ 623897 aff1…689b91cc ]---[ 555 blk/s | 728 tx/s | 24113626 gas/s  //··· 0/1 peers, 658919 downloaded, 0+34981 queued ···//  2936000 (267776) bl  1050240 (8512) ex ]
[ 625961 2d9e…6a18315e ]---[ 412 blk/s | 612 tx/s | 23015200 gas/s  //··· 0/1 peers, 658919 downloaded, 0+32933 queued ···//  2575680 (-360320) bl  1027488 (-22752) ex ]
INFO:ethsync::chain: Disconnected 48:unknown
INFO:ethsync::chain: Connected 48:Parity/0.9.0/x86_64-gnu-linux
thread 'IO Worker #1' panicked at 'ChainSync: new peer already exists', sync/src/chain.rs:299
note: Run with `RUST_BACKTRACE=1` for a backtrace.
thread 'IO Worker #1' panicked at 'called `Result::unwrap()` on an `Err` value: Any', ../src/libcore/result.rs:746
```

### PR DESCRIPTION
**Pull request by arkpar**
fixes #419

### CODE REVIEW

**Comment by arkpar** [comment]
Propagation logic was changed a bit. Check for latest peer hash being too far behind has been removed - we don't know how far it has synced from other peers and should not keep it in the dark. Instead there is now a limit on how many blocks/hashes to send at once.

File: sync/src/chain.rs [hunk 1]
```diff
@@ -437,6 +448,10 @@ impl ChainSync {
 		trace!(target: "sync", "{} -> NewBlock ({})", peer_id, h);
 		let header: BlockHeader = try!(header_rlp.as_val());
  		let mut unknown = false;
+		{
+			let peer = self.peers.get_mut(&peer_id).expect("ChainSync: unknown peer");
```
Comment (gavofyork) [inline sync/src/chain.rs]: this `expect` doesn't look like it's a fundamental logic error. if it is, add a comment explaining why it can never ever happen and other pre-condition `assert!`s in the code to make the proof clear.

Comment (gavofyork) [inline sync/src/chain.rs]: i notice that there are others in the code, so happy for the whole lot to be cleared up in a later PR if preferable.

**Comment by gavofyork** [comment]
quite a logically complex PR - a bit of explanation of what's going on would be appreciated.

File: sync/src/chain.rs (hunk 1 above)
Comment (arkpar) [inline sync/src/chain.rs]: This here is a logic error, the network layer is not supposed to send us packets for unregistered peer ids

Comment (arkpar) [inline sync/src/chain.rs]: Better fix that now

File: sync/src/chain.rs [hunk 2]
```diff
@@ -162,6 +162,8 @@ struct PeerInfo {
 	asking: PeerAsking,
 	/// A set of block numbers being requested
 	asking_blocks: Vec<BlockNumber>,
+	/// Holds requested header hash if currently requesting block header by hash
+	asking_hash: Option<H256>,
```
Comment (arkpar) [inline sync/src/chain.rs]: Normally headers and bodies are downloaded by number, unless downloading a header known from NewBlockHashes packet. 
Currently, if two NewBlockHash packets with the same hash arrive at the same time this may result in same header being requested twice.
This was added to keep track of the requested hash.

File: sync/src/chain.rs [hunk 3]
```diff
@@ -437,6 +448,10 @@ impl ChainSync {
 		trace!(target: "sync", "{} -> NewBlock ({})", peer_id, h);
 		let header: BlockHeader = try!(header_rlp.as_val());
  		let mut unknown = false;
+		{
+			let peer = self.peers.get_mut(&peer_id).expect("ChainSync: unknown peer");
+			peer.latest = header.hash();
```
Comment (arkpar) [inline sync/src/chain.rs]: Update peer's latest hash regardless if the block is known or not, this prevents sending out blocks peer already knows

File: sync/src/chain.rs [hunk 4]
```diff
@@ -844,6 +865,14 @@ impl ChainSync {
 		}
 	}
 
+	/// Generic packet sender
+	fn send_packet(&mut self, sync: &mut SyncIo, peer_id: PeerId, packet_id: PacketId, packet: Bytes) {
```
Comment (arkpar) [inline sync/src/chain.rs]: This is used to send out blocks/hashes/transactions. Does not change peer `asking` status

File: sync/src/chain.rs [hunk 5]
```diff
@@ -486,11 +497,14 @@ impl ChainSync {
...
 		}
 		trace!(target: "sync", "{} -> NewHashes ({} entries)", peer_id, r.item_count());
-		let hashes = r.iter().map(|item| (item.val_at::<H256>(0), item.val_at::<U256>(1)));
-		let mut max_height: U256 = From::from(0);
+		let hashes = r.iter().map(|item| (item.val_at::<H256>(0), item.val_at::<BlockNumber>(1)));
+		let mut max_height: BlockNumber = 0;
 		for (rh, rd) in hashes {
 			let h = try!(rh);
 			let d = try!(rd);
+			if self.downloading_hashes.contains(&h) {
```
Comment (arkpar) [inline sync/src/chain.rs]: Check if this is already being request

File: sync/src/chain.rs [hunk 6]
```diff
@@ -1152,15 +1178,19 @@ impl ChainSync {
...
-		let peers = self.propagade_new_hashes(io);
-		trace!(target: "sync", "Sent new hashes to peers: {:?}", peers);
 	}
 
 	/// should be called once chain has new block, triggers the latest block propagation
 	pub fn chain_blocks_verified(&mut self, io: &mut SyncIo) {
-		let peers = self.propagade_blocks(io);
-		trace!(target: "sync", "Sent latest block to peers: {:?}", peers);
+		let chain = io.chain().chain_info();
+		if (((chain.best_block_number as i64) - (self.last_send_block_number as i64)).abs() as BlockNumber) < MAX_PEER_LAG_PROPAGATION {
```
Comment (arkpar) [inline sync/src/chain.rs]: See top comment. This check is in cpp client also

**Comment by NikVolf** [comment]
lgtm
needs merging with master
