### PR TITLE
Fix contract queries bug

### LINKED ISSUE #4520: Contract constant return function of bytes32 array show wrong data
I'm interacting to a contract that returns a bytes32 array, when I query this function, parity shows wrong data.

Parity result:
image

Expected result:
image

For debug: https://testnet.etherscan.io/address/0x22240d285d8e7e2d38f5257298e93e29a74163c0#code

### PR DESCRIPTION
**Pull request by ngotchac**
Fixes #4520

Add an option to the `call` method (for functions of a contract) to output the raw tokens (`Token` class, with `type` and `value` attributes) instead of `token.value`.

Fixes some UI and logic bugs in the Address Selector too.

### CODE REVIEW

File: js/src/views/Contract/Queries/inputQuery.js [hunk 1]
```diff
@@ -54,18 +54,33 @@ export default class InputQuery extends Component {
           className={ styles.methodTitle }
           title={ name }
         />
+        { this.renderError() }
         { this.renderContent() }
       </Card>
     );
   }
 
+  renderError () {
```
Comment (jacogr) [inline js/src/views/Contract/Queries/inputQuery.js]: We should really be using `newError` so we UI-wide consistent display.
