### PR TITLE
Correct log index in transaction receipt

### LINKED ISSUE #3601: Various differences returned by 'geth' vs. 'parity' RPC
I ran RPC requests against both 'geth 1.5.2-stable' and 'parity 1.4.4-beta' for about 1,000 randomly selected blocks.  I found the following differences in the returned JSON data between the two:

**1) 'geth' returns `nonce` field from `eth_getBlockByNumber(x,true)`, Parity does not**

According to the documentation (https://github.com/ethereum/wiki/blob/master/JSON-RPC.md#eth_getblockbyhash), `nonce` should be returned by getBlockNumber.

**2) 'geth' returns the fields `from`, `to`, and `root` from `eth_getTransactionReceipt(addr)`, Parity does not**

This time, according to the documentation (https://github.com/ethereum/wiki/blob/master/JSON-RPC.md#eth_gettransactionreceipt), 'geth' is wrong. These fields are not
part of the receipt.

**2) Both clients return 'r', 's', and 'v' fields in the transaction from eth_getNumberByBlock(x,true) call**

According to the documentation (https://github.com/ethereum/wiki/blob/master/JSON-RPC.md#eth_gettransactionbyhash), these fields are not part of the transaction data and are therefore extraneous. This may be a bug in the documentation. I'm not sure. Please advise.

**4) 'geth' removes leading zeros from a transaction's `r` and `s` fields, Parity does not.**

Parity inserts zeros after the '0x' to pad the length of the value for these fields to 32 bytes. Since these fields are not documented, I don't know if they should be considered `QUANTITY` or `DATA`. If `DATA`, then Parity is right, if `QUANTITY` then 'geth' is right. I suspect Parity is right.

**6) 'geth' and Parity disagree on the value of the transaction's `v` field.**

For every transaction returned by `eth_getBlockByNumber`, 'geth' returns values of either `0x1b` or `0x1c`. Parity returns either `0` or `1` respectively. Since it's not documented, I don't know the correct value, but they do differ.

**7) Parity numbers the `logIndex` field of the receipts `logs` per transaction. 'geth' numbers the logs per block. The documents say it should be per block, but this may change. Both Parity and 'geth' start their numbering from '0' which may conflict with `null` value in C++ code.**

This is either a bug in Parity (https://github.com/ethcore/parity/issues/3537) or the documentation. There is an issue reported in `geth` discussing this as a bug in the docs (https://github.com/ethereum/go-ethereum/issues/2028).

### PR DESCRIPTION
**Pull request by tomusdrw**
Fixes `log_index` to mean `log index in block` consistently.
Introduces `transaction_log_index`.

Closes #3601, #2075, #3537

### CODE REVIEW

File: ethcore/src/client/client.rs [hunk 1]
```diff
@@ -1535,6 +1499,52 @@ impl Drop for Client {
 	}
 }
 
+fn transaction_receipt(transaction: Option<LocalizedTransaction>, receipts: Option<Vec<Receipt>>) -> Option<LocalizedReceipt> {
+	let tx_and_sender = transaction
+		.and_then(|tx| tx.sender().ok().map(|sender| (tx, sender)));
```
Comment (rphmeier) [inline ethcore/src/client/client.rs]: having this check within the body (and corresponding match for the output) is a bit weird.
`fn transaction_receipt(LocalizedTransaction, Address, Vec<Receipt>) -> LocalizedReceipt` seems like a cleaner interface.

a comment explaining what it does would be nice too. although it seems to me that actually you just need a `fn(Transaction, Address, Receipt, usize)` to do the same thing.

Comment (tomusdrw) [inline ethcore/src/client/client.rs]: This function is not really needed at all, but it is very difficult to test `Client::transaction_receipt` so I wanted to move as much logic as possible here to be able to test it properly.

Also most of the options could be replaced with `.expect("Blockchain database is never pruned and stays consistent.")` but I think current approach with `.and_then` chain is more future proof.

I will move `Options` to `Client::transaction_receipt`
