### PR TITLE
Several fixes to the Wallet in general

### LINKED ISSUE #4304: Multisig wallet contract doesn't throw when sub-call throws.
Why i cant send ICN from my contract? Its says out of gas
Parity 1.5.0

### PR DESCRIPTION
**Pull request by ngotchac**
Closes #4304 

Other fixes (asked by @tomusdrw)
- [x] No warning in the Transfert modal if it would need confirmations (above remaining daily limit)
- [x] Page needs a refresh to show pending transactions (could not reproduce...)
- [x] Improve the Settings modifications
- [x] Click on notification when Wallet receives something doesn't go to the wallet page (but the account page)

### CODE REVIEW

File: js/src/modals/WalletSettings/walletSettings.js [hunk 1]
```diff
@@ -51,12 +52,27 @@ class WalletSettings extends Component {
       return (
         <Modal
           visible
-          title='rejected'
+          title={
+            <FormattedMessage
+              id='ui.walletSettings.rejected.title'
```
Comment (jacogr) [inline js/src/modals/WalletSettings/walletSettings.js]: Can we just make it `walletSettings.*`? `ui.*` is for components under `~/ui` - will just flatten out the produced files as well.

Comment (ngotchac) [inline js/src/modals/WalletSettings/walletSettings.js]: Sure, don't know why I put this...

Comment (ngotchac) [inline js/src/modals/WalletSettings/walletSettings.js]: Done
