### PR TITLE
Fix Token Reg Dapp issues in Firefox

### LINKED ISSUE #4348: TokenReg validation doesn't work in Firefox
Also it doesn't display quite nice.
screenshot from 2017-01-30 10-31-15

### PR DESCRIPTION
**Pull request by ngotchac**
Fixes #4348

@tomusdrw I couldn't reproduce the modal layout issue, but fixed one. Let me know if it still breaks on your side.

### CODE REVIEW

**Comment by tomusdrw** [comment]
Yes, layout looks fine although validation is still not working (Firefox 50.1.0).
To reproduce:
1. Click "Register a new token"
2. Enter any 3 characters to "Token TLA"

It will always indicate that TLA should be 3 characters long, bluring input doesn't help.

File: js/src/dapps/tokenreg/Inputs/Text/input-text.js [hunk 1]
```diff
@@ -105,22 +105,22 @@ export default class InputText extends Component {
     const { validationType, contract } = this.props;
     const validation = validate(value, validationType, contract);
 
-    if (validation instanceof Promise) {
```
Comment (derhuerst) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: 👍

Comment (ngotchac) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: Yep, this wasn't working in Firefox...

Comment (derhuerst) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: and we shouldn't do it anyway. there's `Promise.resolve` and `npm i is-promise`

**Comment by jacogr** [comment]
Issue for the TLA validation - https://github.com/ethcore/parity/issues/4334

File: js/src/dapps/tokenreg/Inputs/Text/input-text.js (hunk 1 above)
Comment (gavofyork) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: why doesn't it work in firefox? it's valid JS isn't it?

Comment (jacogr) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: It doesn't work reliably with the `es6-promise` shim, which I'm guessing is included in FF. (`Bluebird` has the same issue.) 

Chrome doesn't show it since it has native Promises.

Comment (derhuerst) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: @gavofyork In JS, it is considered bad practice to assert `instanceof` in these cases. We only care about getting a thenable interface, which `Promise.resolve` should happily accept. See https://github.com/then/is-promise/issues/6

File: js/src/dapps/tokenreg/Inputs/Text/input-text.js [hunk 2]
```diff
@@ -105,22 +105,22 @@ export default class InputText extends Component {
...
+    }, 50);
 
-      return validation
-        .then(validation => {
-          this.setValidation({
-            ...validation,
-            disabled: false,
-            loading: false
-          });
+    return Promise.resolve(validation)
```
Comment (jacogr) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: +1

File: js/src/dapps/tokenreg/Inputs/Text/input-text.js [hunk 3]
```diff
@@ -105,22 +105,22 @@ export default class InputText extends Component {
     const { validationType, contract } = this.props;
     const validation = validate(value, validationType, contract);
 
-    if (validation instanceof Promise) {
+    const loadingTimeout = setTimeout(() => {
       this.setState({ disabled: true, loading: true });
+    }, 50);
```
Comment (jacogr) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: Doing this always feels very hacky, i.e. you are working around something you shouldn't be doing :) Only a mustn't-grumble.

Comment (ngotchac) [inline js/src/dapps/tokenreg/Inputs/Text/input-text.js]: Hmmm... It's more that it's not necessary to change the state twice if the request resolves in less than 50ms, no ?
