### PR TITLE
Fixed race condition in trace import

### LINKED ISSUE #2475: Parity crashes at some blocks when running with --pruning archive
Doing a sync with
`parity --tracing on --mode active --pruning archive`
Currently crashes parity on block 2371684.

Can be resumed, but I'm not sure if the db is still consistent.

```
...
2016-10-05 13:01:53 UTC Syncing #2371630 8fc3…d02e      1 blk/s   25 tx/s   1 Mgas/s       0+ 7957 Qed   #2379640    0/25/25 peers      2 KiB db    6 MiB chain   57 MiB queue   12 MiB sync

thread 'IO Worker #1' panicked at 'Traces database is incomplete.', ../src/libcore/option.rs:700
note: Run with `RUST_BACKTRACE=1` for a backtrace.
2016-10-05 13:01:59 UTC Finishing work, please wait...
2016-10-05 13:01:59 UTC Stage 3 block verification failed for #2371684 (b58f…9b1a)
Error: Block(UnknownParent(0880fcfc8a501cc8c7dfd000d50fb1eb02a4f9ec65363bc73c7babb677cf1c12))
```
Parity
  version Parity/v1.4.0-unstable-48bb890-20161003/x86_64-linux-gnu/rustc1.12.0

### PR DESCRIPTION
**Pull request by arkpar**
probably fixes #2475

### CODE REVIEW

File: ethcore/src/trace/db.rs [hunk 1]
```diff
@@ -276,12 +266,25 @@ impl<T> TraceDatabase for TraceDB<T> where T: DatabaseExtras {
 				// all traces are expected to be found here. That's why `expect` has been used
 				// instead of `filter_map`. If some traces haven't been found, it meens that
 				// traces database is corrupted or incomplete.
-				.map(|block_hash| self.traces(block_hash).expect("Traces database is incomplete."))
```
Comment (arkpar) [inline ethcore/src/trace/db.rs]: The trace might have been removed by garbage collection at this point

File: ethcore/src/trace/db.rs [hunk 2]
```diff
@@ -276,12 +266,25 @@ impl<T> TraceDatabase for TraceDB<T> where T: DatabaseExtras {
...
-				.map(|block_traces| block_traces.bloom())
+				.map(|block_hash| if block_hash == &request.block_hash {
+					request.traces.bloom()
+				} else {
+					self.traces(block_hash).expect("Traces database is incomplete.").bloom()
```
Comment (gavofyork) [inline ethcore/src/trace/db.rs]: not a proof.
