### PR TITLE
Fixed losing queued blocks on error

### LINKED ISSUE #1442: Sync failed.
Trace:

http://pastebin.com/3ixkumBz

### PR DESCRIPTION
**Pull request by arkpar**
fixes #1442

### CODE REVIEW

File: ethcore/src/client/client.rs [hunk 1]
```diff
@@ -296,7 +296,7 @@ impl<V> Client<V> where V: Verifier {
 			let closed_block = self.check_and_close_block(&block);
 			if let Err(_) = closed_block {
 				invalid_blocks.insert(header.hash());
-				break;
```
Comment (arkpar) [inline ethcore/src/client/client.rs]: verification loop would break here and leave the rest of the blocks in lmbo
