### PR TITLE
Sync: Propagate uncles and fix status reporting

### LINKED ISSUE #1110: eth_syncing / web3_eth_issyncing shouldn't be kicking off as blocks are mined
Parity reports a sync for every block that gets imported from the network, even after the blockchain has done its initial sync. With the current behaviour it differs from geth, which only reports a syncing status if it has some real catching up to do (being (much) more than 1 block behind from the rest of the network).

@gavofyork on gitter:
> i guess it depends on what you call "real catching up" 
> but yes - it shouldn't be kicking off as blocks are mined

`version Parity/v1.2.0-unstable-dcc695d-20160517/x86_64-macos/rustc1.8.0`

### PR DESCRIPTION
**Pull request by arkpar**
Fixes #1110 and hopefully #1130

### CODE REVIEW

File: ethcore/src/blockchain/blockchain.rs [hunk 1]
```diff
@@ -529,7 +534,7 @@ impl BlockChain {
 		let mut ret = Vec::new();
 		for a in self.ancestry_iter(parent.clone()).unwrap().skip(1).take(uncle_generations) {
 			ret.extend(self.block_details(&a).unwrap().children.iter()
-				.filter_map(|h| if excluded.contains(h) { None } else { self.block_header(h) })
+				.filter_map(|h| if excluded.contains(h) { None } else { Some(h) })
```
Comment (rphmeier) [inline ethcore/src/blockchain/blockchain.rs]: could this just be `filter(|h| excluded.contains(h)`?
