### PR TITLE
Fix focus on Modal

### LINKED ISSUE #3814: Focus remains on the background page when a popup shows up
To reproduce:

- open a popup (transfer, shapeshift, etc...)
- don´t click anywhere
- hit TAB a few times

=> you will see the focus jumping in the main page under the modal "popup".

### PR DESCRIPTION
**Pull request by ngotchac**
Closes  #3814

Focus on the Modal when it opens.

### CODE REVIEW

File: js/src/ui/Container/container.js [hunk 1]
```diff
@@ -30,15 +30,22 @@ export default class Container extends Component {
...
   }
 
   render () {
-    const { children, className, compact, light, style } = this.props;
+    const { children, className, compact, light, style, tabIndex } = this.props;
     const classes = `${styles.container} ${light ? styles.light : ''} ${className}`;
 
+    const props = {};
+
+    if (Number.isInteger(tabIndex)) {
```
Comment (jacogr) [inline js/src/ui/Container/container.js]: Not sure I get this 100% - we are getting tabIndex from props and then assign it back into props again.

File: js/src/ui/Modal/modal.js [hunk 2]
```diff
@@ -49,6 +50,14 @@ class Modal extends Component {
     waiting: PropTypes.array
   }
 
+  componentDidMount () {
+    const e = ReactDOM.findDOMNode(this.refs.dialog);
```
Comment (jacogr) [inline js/src/ui/Modal/modal.js]: Would have preferred `const element = ReactDOM...` instead of the single `e` that could mean error, event, element, etc. (Not really gaining anything by being cryptic)

**Comment by derhuerst** [comment]
Can confirm that this fixes the tabbing problem.
