### PR TITLE
Network tracing cleanup

### LINKED ISSUE #538: Clear up Token registration problems
I keep getting messages like these. Presumably they're unimportant.

```
2016-02-29 15:20:04 DEBUG:ethcore_util::network::connection: Failed to reregister Token(26), Error { repr: Os { code: 2, message: "No such file or directory" } }
```

### PR DESCRIPTION
**Pull request by arkpar**
fixes #538

### CODE REVIEW

File: util/src/network/host.rs [hunk 1]
```diff
@@ -170,29 +170,37 @@ pub struct NetworkContext<'s, Message> where Message: Send + Sync + Clone + 'sta
 	io: &'s IoContext<NetworkIoMessage<Message>>,
 	protocol: ProtocolId,
 	sessions: Arc<RwLock<Slab<SharedSession>>>,
-	session: Option<StreamToken>,
```
Comment (arkpar) [inline util/src/network/host.rs]: Shared session pointer is used to output proper client id instead of "unknown" on disconnect and to guarantee that io handler is dealing with the same session.

**Comment by gavofyork** [comment]
code quality looks fine but i'm not familiar enough with this part of the codebase to sign off on the logic.
