### PR TITLE
More sync fixes

### LINKED ISSUE #662: Sync stopped
pi.parity.io stopped syncing on #1113722

### PR DESCRIPTION
**Pull request by arkpar**
Fixes #662

### CODE REVIEW

File: sync/src/chain.rs [hunk 1]
```diff
@@ -656,10 +662,7 @@ impl ChainSync {
 		let mut needed_numbers: Vec<BlockNumber> = Vec::new();
 
 		if self.have_common_block && !self.headers.is_empty() && self.headers.range_iter().next().unwrap().0 == self.current_base_block() + 1 {
-			for (start, ref items) in self.headers.range_iter() {
-				if needed_bodies.len() >= MAX_BODIES_TO_REQUEST {
-					break;
-				}
+			if let Some((start, ref items)) = self.headers.range_iter().next() {
```
Comment (arkpar) [inline sync/src/chain.rs]: Download bodies only for the validated part of the header-chain

File: sync/src/chain.rs [hunk 2]
```diff
@@ -844,18 +847,9 @@ impl ChainSync {
...
-				let header_id = HeaderId {
-					transactions_root: header_to_delete.transactions_root(),
-					uncles: header_to_delete.uncles_hash()
-				};
-				self.header_ids.remove(&header_id);
-			}
-			self.downloading_bodies.remove(&n);
-			self.downloading_headers.remove(&n);
-		}
+		self.downloading_bodies.clear();
```
Comment (arkpar) [inline sync/src/chain.rs]: Clear everything to be safe
