### PR TITLE
Fix uncle getter

### LINKED ISSUE #1057: RPC eth_getUncleByBlockNumberAndIndex returns null for a block which 100% has uncle
Geth return valid block for the following RPC request:
```bash
curl -X POST http://127.0.0.1:8545 -d '{"jsonrpc":"2.0","method":"eth_getUncleByBlockNumberAndIndex","params":["0xdbf9e", "0x0"],"id":0}'
```

but parity which is synced with `--pruning fast` returns `null`. I will resync without pruning and report.
Testnet.

### PR DESCRIPTION
**Pull request by gavofyork**
Uncle blocks don't necessarily have BlockDetails, so can't get total
difficulty directly.
Closes #1057

### CODE REVIEW

File: rpc/src/v1/impls/eth.rs [hunk 1]
```diff
@@ -138,8 +138,8 @@ impl<C, S, A, M, EM> EthClient<C, S, A, M, EM>
 					gas_limit: uncle.gas_limit,
 					logs_bloom: uncle.log_bloom,
 					timestamp: U256::from(uncle.timestamp),
-					difficulty: uncle.difficulty,
-					total_difficulty: difficulty,
+					difficulty: uncle.difficulty + parent_difficulty,
```
Comment (arkpar) [inline rpc/src/v1/impls/eth.rs]: Is this correct? Isn't that `total_difficulty`?

File: rpc/src/v1/impls/eth.rs [hunk 2]
```diff
@@ -138,8 +138,8 @@ impl<C, S, A, M, EM> EthClient<C, S, A, M, EM>
...
+					total_difficulty: uncle.difficulty,
```
Comment (debris) [inline rpc/src/v1/impls/eth.rs]: I think it should be:
```diff
-					difficulty: uncle.difficulty + parent_difficulty,
+					difficulty: uncle.difficulty,
-					total_difficulty: uncle.difficulty,
+					total_difficulty: uncle.difficulty + parent_difficulty,
```
