### PR TITLE
Sync fixed again

### LINKED ISSUE #730: Sync hanged on zhadum.parity.io @ #565333 after ancient block imported

### PR DESCRIPTION
**Pull request by arkpar**
fixes #730, #728, and probably #727

### CODE REVIEW

File: sync/src/chain.rs [hunk 1]
```diff
@@ -498,9 +501,10 @@ impl ChainSync {
 				Ok(_) => {
 					if self.current_base_block() < header.number {
 						self.last_imported_block = Some(header.number);
+						self.last_imported_hash = Some(header.hash());
```
Comment (arkpar) [inline sync/src/chain.rs]: This was the main problem. Just forgot to update `last_imported_hash` here
