### PR TITLE
fixed trace_transaction crash when block contained suicide

### LINKED ISSUE #1772: trace_transaction causes node to crash for txhash 0x55943f2d..
When calling trace_transaction for Txhash 0x55943f2d6d0189946cec6ef0b37fa3c4dc158b7e143a76b24ee87ba4ab7cbe6a causes the node to crash with the following error

---

C:\>"C:\Program Files\Ethcore\Parity\parity.exe" --tracing on --port 30305 --jso
nrpc-port 8546
2016-07-29 15:44:53 UTCStarting Parity/v1.3.0-unstable-57faa37-20160729/x86_64-w
indows-msvc/rustc1.10.0
2016-07-29 15:44:53 UTCUsing state DB journalling strategy fast
2016-07-29 15:44:53 UTCImport geth accounts failed. The filename, directory name
, or volume label syntax is incorrect. (os error 123)
2016-07-29 15:44:53 UTCConfigured for Frontier/Homestead using Ethash engine
2016-07-29 15:44:59 UTCPublic node URL: enode://920a46addf49e477344e6745d3f0a318
97e3a35f7034d793bcc4413d011db6e287a2d6dc3795d18573bc01f92f5d09f433fc40b38e07db31
f57d3410e9338b2e@127.0.0.1:30305
thread '<unnamed>' panicked at 'DecodeError: RlpIsTooShort', Users\XX\.cargo\gi
t\checkouts\parity-6ba620efeffb2216\master\util\src\rlp\rlpin.rs:119
stack backtrace:
   0:     0x7ff64ee0f032 - <unknown>
   1:     0x7ff64ee0e61d - <unknown>
   2:     0x7ff64edee29d - <unknown>
   3:     0x7ff64ee113db - <unknown>
   4:     0x7ff64edef6df - <unknown>
   5:     0x7ff64e906ecb - <unknown>
   6:     0x7ff64e92010b - <unknown>
   7:     0x7ff64e640185 - <unknown>
   8:     0x7ff64ed299bf - <unknown>
   9:     0x7ff64ed2b6bc - <unknown>
  10:     0x7ff64ed2a54d - <unknown>
  11:     0x7ff64ed53305 - <unknown>
  12:     0x7ff64e85ff31 - <unknown>
  13:     0x7ff64e855706 - <unknown>
  14:     0x7ff64e855c6b - <unknown>
  15:     0x7ff64e85626e - <unknown>
  16:     0x7ff64e85549b - <unknown>
  17:     0x7ff64e8517a3 - <unknown>
  18:     0x7ff64e8477f5 - <unknown>
  19:     0x7ff64e84646b - <unknown>
  20:     0x7ff64e86be3c - <unknown>
  21:     0x7ff64ee14791 - <unknown>
  22:     0x7ff64e86c11b - <unknown>
  23:     0x7ff64ee0cd03 - <unknown>
  24:     0x7ffcd44413d1 - BaseThreadInitThunk
2016-07-29 15:45:02 UTCFinishing work, please wait...
thread '<main>' panicked at 'called `Result::unwrap()` on an `Err` value: Closed
', ../src/libcore\result.rs:785
stack backtrace:
   0:     0x7ff64ee0f032 - <unknown>
   1:     0x7ff64ee0e61d - <unknown>
   2:     0x7ff64edee29d - <unknown>
   3:     0x7ff64ee113db - <unknown>
   4:     0x7ff64edef6df - <unknown>
   5:     0x7ff64ee1101c - <unknown>
   6:     0x7ff64ee15255 - <unknown>
   7:     0x7ff64eb55bd0 - <unknown>
   8:     0x7ff64eb55ad9 - <unknown>
   9:     0x7ff64e86c592 - <unknown>
  10:     0x7ff64e523587 - <unknown>
  11:     0x7ff64e4a56c0 - <unknown>
  12:     0x7ff64e491b2f - <unknown>
  13:     0x7ff64e513432 - <unknown>
  14:     0x7ff64ee0dffc - <unknown>
  15:     0x7ff64ee14791 - <unknown>
  16:     0x7ff64ee0dd34 - <unknown>
  17:     0x7ff64efb86e7 - secp256k1_schnorr_verify
  18:     0x7ffcd44413d1 - BaseThreadInitThunk

### PR DESCRIPTION
**Pull request by debris**
fixes #1772

fix is in only in`ethcore/src/types/trace_types/trace.rs`. The rest of the pr contains only tests

### CODE REVIEW

File: ethcore/src/trace/db.rs [hunk 1]
```diff
@@ -423,6 +423,7 @@ mod tests {
 		}
 	}
 
+	#[derive(Clone)]
```
Comment (arkpar) [inline ethcore/src/trace/db.rs]: Should be `cfg_attr` if only used in test code

Comment (debris) [inline ethcore/src/trace/db.rs]: it's a part of `mod tests` already
