### PR TITLE
Fix address and accounts links

### LINKED ISSUE #4314: Make address click-through to Parity view (non-external)
As requested by @tomusdrw 

TxList links for addresses to go through to `#/address/<address>` for accounts to go through to `#/accounts/<address>`

### PR DESCRIPTION
**Pull request by ngotchac**
Closes #4314 

In Signer and Transaction lists, redirect the links to Parity UI and not Etherscan

### CODE REVIEW

**Comment by jacogr** [comment]
Failing tests.

**Comment by ngotchac** [comment]
Fix test (and added 2 actually)

File: js/src/views/Signer/store.js [hunk 1]
```diff
@@ -17,13 +17,16 @@
 import { isEqual } from 'lodash';
 import { action, observable } from 'mobx';
 
-export default class Store {
+export default class SignerStore {
   @observable balances = {};
   @observable localHashes = [];
 
-  constructor (api, withLocalTransactions = false) {
+  externalLink = '';
```
Comment (jacogr) [inline js/src/views/Signer/store.js]: _externalLink for non-exposed internal variables. (As per rest of the class)

File: js/src/ui/TxList/TxRow/txRow.js [hunk 2]
```diff
@@ -138,4 +139,30 @@ export default class TxRow extends Component {
...
+
+    return `/addresses/${address}`;
+  }
 }
+
+function mapStateToProps (initState) {
+  const { accounts } = initState.personal;
+  const accountAddresses = Object.keys(accounts);
+
+  return () => {
```
Comment (jacogr) [inline js/src/ui/TxList/TxRow/txRow.js]: Why not a simple

```
return {
  accountAddresses
};
```

(As opposed to the function?)

**Comment by jacogr** [comment]
I'm just wondering if `externalLink` is anything but `''` anywhere? Adds a lot of complexity (especially in terms of yet more change listeners), however I'm not seeing where it is set to any value that is not the default.

(I may be going blind)

File: js/src/ui/TxList/TxRow/txRow.js (hunk 2 above)
Comment (ngotchac) [inline js/src/ui/TxList/TxRow/txRow.js]: It's only so it doesn't re-render on every Redux dispatched action (since the same Object is thus returned)

**Comment by ngotchac** [comment]
It's mainly for the embedded Parity Bar for the Chrome Extension ! ;)
