### PR TITLE
block: enforce gas limit falls within engine bounds

### LINKED ISSUE #3760: minGasLimit/gasLimitBoundDivisor is not taken into account when creating pending block
Together with `--gas-floor-target` below `minGasLimit` leads the node to mine invalid blocks (that presumably are short-circuited into the chain without proper verification that would reject them)

Reported on gitter:

> I was testing a private chain with extremely large (pi*10M) genesis block gas limit and a gas minimum equal to that. I mined blocks on one node and it worked just fine, but another node refused to sync the chain because block 1 gas limit was below minimum. I later checked that the gas limit indeed decreased. My guess is that the default value for `--gas-floor-target` made the mining node decrease the limit, then the client did not properly validate a block that it has just mined, and broadcast it, while the listening node tried to validate it and failed. Effectively the same thing happened when I next also set an effectively infinite `gasLimitBoundDivisor` to prevent the gas limit to move altogether as per (YP:45-46). I guess I can work around it all by setting a proper `--gas-floor-target`, but I think it should not "override" how the gas limit evolution is specified by the chain spec params and definitely Parity should not mine blocks that turn out to be invalid.

### PR DESCRIPTION
**Pull request by rphmeier**
Fixes #3760

Ideally I think the best thing to do would be to no longer expose `CommonParams` and allow engines to internally manage the ranges while exposing nothing more than a simple validation/creation interface as a black box.

### CODE REVIEW

File: ethcore/src/engines/mod.rs [hunk 1]
```diff
@@ -125,8 +125,9 @@ pub trait Engine : Sync + Send {
 		self.verify_block_basic(header, None).and_then(|_| self.verify_block_unordered(header, None))
 	}
 
-	/// Don't forget to call Super::populate_from_parent when subclassing & overriding.
```
Comment (rphmeier) [inline ethcore/src/engines/mod.rs]: this comment didn't make much sense so I didn't see a reason to keep it.
