### PR TITLE
fix deadlock in queue drop

### LINKED ISSUE #3885: test_mem_limit test can deadlock

### PR DESCRIPTION
**Pull request by rphmeier**
Closes #3885

### CODE REVIEW

File: ethcore/src/verification/queue/mod.rs [hunk 1]
```diff
@@ -681,6 +681,12 @@ impl<K: Kind> Drop for VerificationQueue<K> {
...
 		self.state.1.notify_all();
 
+		// acquire this lock to force threads to reach the waiting point
+		// if they're in-between the exit check and the more_to_verify wait.
+		{
+			let _more = self.verification.more_to_verify.lock().unwrap();
+		}
+
 		// wake up all threads waiting for more work.
 		self.more_to_verify.notify_all();
```
Comment (arkpar) [inline ethcore/src/verification/queue/mod.rs]: This call should be made under the lock as well.

Comment (rphmeier) [inline ethcore/src/verification/queue/mod.rs]: i think that would cause a deadlock in itself, since any notified thread needs to have the lock returned from the wait call.
